platform: "tensorrt_plan"
max_batch_size: 1
  input [
    {
      name: "input"
      data_type: TYPE_FP32
      dims: [ 64000 ]
    }
  ]
  output [
    {
      name: "output"
      data_type: TYPE_FP32
      dims: [ 256 ]
    }
  ]